[book]
authors = ["Roman Voronkin"]
language = "ru"
multilingual = false
src = "src"
title = "Электронный учебник"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[output]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = true
copy-fonts = true
git-repository-url = "https://github.com/new-divos/edu-book"
git-repository-icon = "fa-github"
additional-css = ['.\.\mdbook-admonish.css', 'css\custom.css']
